Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  config.vm.define "zoukaddoS" do |server|
    server.vm.hostname = "zoukaddoS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "zoukaddoS"
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "file", source: "confs", destination: "/home/vagrant/confs"
    server.vm.provision "shell", path: "scripts/setup-server.sh"
  end
end
