Vagrant.configure("2") do |config|
  config.vm.define "zoukaddoS" do |server|
    server.vm.box = "bento/ubuntu-22.044"
    server.vm.hostname = "zoukaddoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/server.sh"
    server.vm.provision "shell", inline: <<-SHELL
      kubectl apply -f /vagrant/confs/deployment.yaml
    SHELL
  end
end
