# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "zoukaddoS" do |server|
    server.vm.hostname = "zoukaddoS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "zoukaddoS"
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "shell", path: "scripts/setup-server.sh"
  end
end
