Vagrant.configure("2") do |config|
  config.vm.define "zoukaddoS" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.hostname = "zoukaddoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/server.sh"
   end

  config.vm.define "zoukaddoSW" do |worker|
    worker.vm.box = "bento/ubuntu-22.04"
    worker.vm.hostname = "zoukaddoSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
